In [ ]:
#problem1
#Qno1
import numpy as np
A=np.empty((2,2))
print(A)

[[4.63516502e-310 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]


In [ ]:
#Qno2
import numpy as np
A = np.ones((4,2))
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Qno3
import numpy as np
filled = np.full((2,2),1)
print(filled)

[[1 1]
 [1 1]]


In [ ]:
#Qno4
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
zero_arr = np.zeros_like(arr)
print(zero_arr)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [ ]:
#Qno5
import numpy as np
new_list=[1,2,3,4,5]
arr = np.array(new_list)
print(arr)

[1 2 3 4 5]


In [1]:
#problem2
#Qno1
import numpy as np
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#Qno2
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Qno3
import numpy as np
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Qno4
import numpy as np
arr = np.random.random(30)
print(arr)
arr_mean = arr.mean()
print("\n", arr_mean)

[0.25316571 0.05804136 0.11192424 0.21356917 0.40160648 0.53838875
 0.72341908 0.38931199 0.77118695 0.69403547 0.38982082 0.49589215
 0.43180007 0.57250565 0.82236922 0.72406099 0.12400481 0.22788642
 0.79845947 0.07163072 0.19752169 0.44729177 0.28108827 0.5822033
 0.85789205 0.13603174 0.07938553 0.37773566 0.21468016 0.83295654]

 0.4273288733847763


In [ ]:
#Qno5
import numpy as np
arr = np.random.random((10,10))
print(arr)
arr_min = arr.min()
arr_max = arr.max()
print("\n", arr_min, arr_max)

[[0.95694992 0.21469665 0.34123915 0.8010515  0.02274428 0.2549822
  0.15958751 0.57089512 0.92552514 0.7462947 ]
 [0.34694739 0.19195436 0.0398015  0.17475267 0.92611159 0.14968315
  0.59069179 0.91818841 0.97608987 0.99674545]
 [0.18343649 0.89990307 0.15720029 0.43872506 0.9099269  0.38547253
  0.61574266 0.48131515 0.49355118 0.8967568 ]
 [0.69208098 0.51866884 0.73149022 0.21876587 0.4358945  0.20594963
  0.96490778 0.2957102  0.72596941 0.98250119]
 [0.83631173 0.2083463  0.47954676 0.6715684  0.78075956 0.74320244
  0.45564489 0.33563334 0.25203191 0.56678889]
 [0.70556833 0.1735209  0.13491861 0.8393214  0.86915787 0.63097178
  0.34190136 0.63856285 0.90693272 0.62405807]
 [0.72041511 0.10751712 0.36615068 0.09596223 0.025117   0.44840899
  0.62020486 0.59082586 0.82624806 0.60088017]
 [0.19949099 0.20435207 0.37848826 0.8092342  0.18708876 0.52282685
  0.25876197 0.36925977 0.21182906 0.8297098 ]
 [0.15910366 0.87292002 0.95319402 0.61846773 0.76036986 0.98025407
  0.41443661 

In [ ]:
#Qno6
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Qno7
import numpy as np
arr = [1,2,0,0,4,0]
rev_arr = np.flip(arr)
print(rev_arr)

[0 4 0 0 2 1]


In [ ]:
#Qno8
import numpy as np
arr = np.ones((4,4))
print("original array: \n", arr)
arr[1:-1,1:-1] = 0
print("Array with 1 on the border and 0 on inside \n", arr)

original array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with 1 on the border and 0 on inside 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#problem3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum_x_y = x+y
sum_v_w = v+w
print("sum of x and y matrix: \n",sum_x_y,"\n")
print("sum of v and w matirx: \n",sum_v_w, "\n")
diff_x_y = x-y
diff_v_w = v-w
print("difference of x and y matrix: \n",diff_x_y,"\n")
print("difference of v and w matrix: \n",diff_v_w, "\n")
prod_x_y = x*y
prod_v_w = v*w
print("product of x and y matrix: \n",prod_x_y,"\n")
print("product of v and w matrix: \n",prod_v_w, "\n")
sqr_x = np.square(x)
sqr_y = np.square(y)
sqr_v = np.square(v)
sqr_w = np.square(w)
print("square of x matrix: \n",sqr_x,"\n")
print("square of y matrix: \n",sqr_y,"\n")
print("square of v matrix: \n",sqr_v,"\n")
print("square of w matrix: \n",sqr_w,"\n")
dot_x_y = np.dot(x,y)
dot_v_w = np.dot(v,w)
print("dot product of x and y matrix: \n",dot_x_y,"\n")
print("dot product of v and w matrix: \n",dot_v_w,"\n")
conc1=np.concatenate((x,y),axis=1)
conc1
conc2=np.concatenate((v,w), axis=0)
conc2

sum of x and y matrix: 
 [[ 6  8]
 [10 13]] 

sum of v and w matirx: 
 [20 22] 

difference of x and y matrix: 
 [[-4 -4]
 [-4 -3]] 

difference of v and w matrix: 
 [-2 -2] 

product of x and y matrix: 
 [[ 5 12]
 [21 40]] 

product of v and w matrix: 
 [ 99 120] 

square of x matrix: 
 [[ 1  4]
 [ 9 25]] 

square of y matrix: 
 [[25 36]
 [49 64]] 

square of v matrix: 
 [ 81 100] 

square of w matrix: 
 [121 144] 

dot product of x and y matrix: 
 [[19 22]
 [50 58]] 

dot product of v and w matrix: 
 219 



array([ 9, 10, 11, 12])

In [2]:
#problem4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

inverse=np.linalg.inv(A)
mult=np.dot(A,inverse)

Equal1=np.dot(A,B)
Equal2=np.dot(B,A)
Equal3=Equal1==Equal2

inverse1=np.transpose(Equal1)
inverse2=np.transpose(B)
inverse3=np.transpose(A)
inverse4=np.dot(inverse2,inverse3)